### ISSUE TITLE
Support BASIC authentication to retrieve helm charts

### ISSUE THREAD

**Issue by rsp9u** [yaamai/k8s-gitsync#11]
BASIC authentication should be supported for the users who use this with private charts repositories.

like this
```yaml
name: something
namespace: somewhere
chart:
  name: something
  version: "1.0.0"
  repo: "http://192.168.0.1:8080/repo/charts/raw/branch/master/dist/"
  auth:
    [type: basic] (needless?)
    username: user
    password: password
```

@yaamai 
What about password hiding and replacing? I think that it's responsibility of users (e.g. CI secret & envsubst before running k8s-gitsync). Let me know your thoughts.
